# Generated by Django 3.1.3 on 2020-12-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
