# Generated by Django 3.1.3 on 2020-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0002_auto_20201203_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('profession', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'pupil',
                'ordering': ['first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
