# Generated by Django 3.1.3 on 2020-12-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0003_pupil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
    ]
